package it.polimi.se2018.controller.controllerEvent;

import it.polimi.se2018.utils.Event;

/**
 * A generic event generated by the controller
 */
public abstract class ControllerEvent extends Event {
    protected ControllerEvent(String emitter, String player) {
        super(emitter, player);
    }
}
