package it.polimi.se2018.controller.controllerEvent;

import it.polimi.se2018.utils.Event;
import it.polimi.se2018.view.VisitableFromView;

/**
 * A generic event generated by the controller
 */
public abstract class ControllerEvent extends Event implements VisitableFromView {
    protected ControllerEvent(String emitter, String player, String receiver) {
        super(emitter, player, receiver);
    }
    protected ControllerEvent(String json){super(json);}
}
