package it.polimi.se2018.controller.states;

import it.polimi.se2018.controller.Controller;
import it.polimi.se2018.model.GameTableMultiplayer;
import it.polimi.se2018.utils.Event;

/**
 * A generic State used by the controller to handle a player event
 */
public abstract class State {
    private Controller controller;

    public State(Controller controller) {
        this.controller = controller;
    }

    /**
     * Handles an event generated by a player
     * @param event the event to handle
     * @param model the model to modify
     * @return the new State for the controller
     */
    abstract public State handleEvent(Event event, GameTableMultiplayer model);

    public Controller getController() {
        return controller;
    }
}
